//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Communication()
        {
            this.CommunicationDatas = new HashSet<CommunicationData>();
        }
    
        public Nullable<System.DateTime> CreatedUtcDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedUtcDateTime { get; set; }
        public string DevicePushId { get; set; }
        public string TargetUserId { get; set; }
        public Nullable<long> PushInfoId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public long CommunicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommunicationData> CommunicationDatas { get; set; }
    }
}
