//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationData
    {
        public int Id { get; set; }
        public string DataKey { get; set; }
        public string DateValue { get; set; }
        public Nullable<System.DateTime> LastUpdatedUtcDateTime { get; set; }
        public Nullable<System.DateTime> CreatedUtcDateTime { get; set; }
        public Nullable<long> CommunicationId { get; set; }
    
        public virtual Communication Communication { get; set; }
    }
}
