//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePush
    {
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string PushId { get; set; }
        public string Platform { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> CreatedUTCDateTime { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
