//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLable
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Label { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedUTCDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedUTCDateTime { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
