//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> PayerId { get; set; }
        public Nullable<int> BeneficiaryId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DeductionAmont { get; set; }
        public Nullable<double> TransferAmount { get; set; }
        public string Currency { get; set; }
        public string PaymentMethod { get; set; }
        public string EventEntryCode { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> CreatedUtcDate { get; set; }
        public Nullable<System.DateTime> UpdatedUtcdate { get; set; }
        public string BarCode { get; set; }
        public Nullable<double> TaxAmount { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
    }
}
