//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nsc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public int Id { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> PaymentAmount { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrial { get; set; }
        public Nullable<System.DateTime> CreatedUtcDate { get; set; }
        public Nullable<System.DateTime> UpdatedUtcDate { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
